name: keuangan
description: Keuangan.
publish_to: "none"
version: 1.0.3+4
environment:
  sdk: ">=3.0.0<4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  page_transition: "^2.0.5"
  flutter_form_builder: ^9.0.0
  form_builder_validators: ^10.0.0
  flutter_spinkit: ^5.1.0
  flutter_secure_storage: ^9.2.2
  get: ^4.6.1
  provider: ^6.0.2
  currency_text_input_formatter: ^2.1.5
  collection: ^1.18.0
  carousel_slider: ^4.2.1
  card_swiper: ^3.0.1
  skeleton_text: ^3.0.1
  awesome_dialog: ^3.2.1
  animated_text_kit: ^4.2.2
  flutter_speed_dial: ^7.0.0
  form_builder_phone_field: ^2.0.1
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: any

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# flutter logo icon
flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logo.png"

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/PlusJakartaSans-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/PlusJakartaSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/PlusJakartaSans-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/PlusJakartaSans-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/PlusJakartaSans-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-SemiBoldItalic.ttf
          style: italic
          weight: 600