name: keuangan
description: Keuangan.
publish_to: "none"
version: 1.0.3+4
environment:
  sdk: ">=3.0.0<4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  page_transition: "^2.0.5"
  flutter_form_builder: ^10.3.0+1
  form_builder_validators: ^11.3.0
  flutter_spinkit: ^5.1.0
  flutter_secure_storage: ^10.0.0
  get: ^4.6.1
  provider: ^6.0.2
  currency_text_input_formatter: ^2.1.5
  collection: ^1.18.0
  card_swiper: ^3.0.1
  skeleton_text: ^3.0.1
  awesome_dialog: ^3.2.1
  animated_text_kit: ^4.2.2
  flutter_speed_dial: ^7.0.0
  form_builder_phone_field: ^3.1.0
  sqflite: ^2.3.3+1
  fl_chart: ^1.1.1
  pdf: ^3.11.3
  excel: ^4.0.6
  share_plus: ^12.0.1
  path_provider: ^2.1.5
  dio: ^5.9.1
  shared_preferences: ^2.5.4
  restart_app: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: any
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"
  
flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logo.png"
  
flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/PlusJakartaSans-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/PlusJakartaSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/PlusJakartaSans-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/PlusJakartaSans-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/PlusJakartaSans-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-SemiBoldItalic.ttf
          style: italic
          weight: 600